### ISSUE TITLE
A bug when testing

### ISSUE THREAD

**Issue by zy-lazytitan** [octree-nn/ognn-pytorch#3]
Thank you very much for making this code available - it is very inspiring.
I just want to forward the pre-trained network, so I downloaded the test.input and checkpoint, then I ran the code `python main.py --config configs/shapenet_eval.yaml SOLVER.ckpt logs/shapenet/shapenet/checkpoints/00300.model.pth`, but it raised the following error.
I guess there's something wrong with the dataset. Look forward to your reply. Thank you！
`Total number of parameters: 2.182M
Logdir: logs/shapenet_eval/test
Load the checkpoint: logs/shapenet/shapenet/checkpoints/00300.model.pth
The start_epoch is 1
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):                                              
  File "/home/l/t/ognn-pytorch/main.py", line 117, in <module>
    OGNSolver.main()
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/thsolver/solver.py", line 439, in main
    cls.worker(0, FLAGS)
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/thsolver/solver.py", line 428, in worker
    the_solver.run()
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/thsolver/solver.py", line 403, in run
    eval('self.%s()' % self.FLAGS.SOLVER.run)
  File "<string>", line 1, in <module>
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/thsolver/solver.py", line 367, in evaluate
    self.eval_epoch(epoch)
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/thsolver/solver.py", line 230, in eval_epoch
    self.eval_step(batch)
  File "/home/l/t/ognn-pytorch/main.py", line 67, in eval_step
    output = self.model.forward(octree_in, octree_out, update_octree=True)
  File "/home/l/t/ognn-pytorch/ognn/ounet.py", line 132, in forward
    output = self.octree_decoder(convs, octree_in, octree_out, update_octree)
  File "/home/l/t/ognn-pytorch/ognn/ounet.py", line 124, in octree_decoder
    octree_out.octree_grow(d + 1)
  File "/home/l/t/ognn-pytorch/ognn/octreed.py", line 123, in octree_grow
    super().octree_grow(depth, update_neigh)
  File "/home/l/anaconda3/envs/ognn/lib/python3.10/site-packages/ocnn/octree/octree.py", line 292, in octree_grow
    self.nnum[depth] = nnum
IndexError: index 4 is out of bounds for dimension 0 with size 4`

**Comment by wang-ps** [comment]
Clone the latest ognn code and use the lastest `ocnn` package (`pip install --upgrade ocnn`).

**Comment by zy-lazytitan** [comment]
Thank you very much! I can now run the code successfully.
